// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvFUvcgxmrY7fDvSj0wga0_howiLzeVnA',
    appId: '1:28670291258:web:916bf1df731e0ec9903403',
    messagingSenderId: '28670291258',
    projectId: 'fir-example-c5095',
    authDomain: 'fir-example-c5095.firebaseapp.com',
    storageBucket: 'fir-example-c5095.appspot.com',
    measurementId: 'G-XVDSYBPBVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl34XZoo8-B6iH1LMijKKIhWIHBRuFAzI',
    appId: '1:28670291258:android:46f70e7e67e742f9903403',
    messagingSenderId: '28670291258',
    projectId: 'fir-example-c5095',
    storageBucket: 'fir-example-c5095.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG067hfpmoYmHkHvtfdBdxGQ3Snq7XHwA',
    appId: '1:28670291258:ios:872ad21c696d4942903403',
    messagingSenderId: '28670291258',
    projectId: 'fir-example-c5095',
    storageBucket: 'fir-example-c5095.appspot.com',
    iosClientId: '28670291258-7o2k6qh5la3sl5vs2cahnij0qb2hrdmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG067hfpmoYmHkHvtfdBdxGQ3Snq7XHwA',
    appId: '1:28670291258:ios:872ad21c696d4942903403',
    messagingSenderId: '28670291258',
    projectId: 'fir-example-c5095',
    storageBucket: 'fir-example-c5095.appspot.com',
    iosClientId: '28670291258-7o2k6qh5la3sl5vs2cahnij0qb2hrdmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseExample',
  );
}
